// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package mock_buyer is a generated GoMock package.
package mock_buyer

import (
	gomock "github.com/golang/mock/gomock"
)

// MockBuyerRepo is a mock of BuyerRepo interface.
type MockBuyerRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBuyerRepoMockRecorder
}

// MockBuyerRepoMockRecorder is the mock recorder for MockBuyerRepo.
type MockBuyerRepoMockRecorder struct {
	mock *MockBuyerRepo
}

// NewMockBuyerRepo creates a new mock instance.
func NewMockBuyerRepo(ctrl *gomock.Controller) *MockBuyerRepo {
	mock := &MockBuyerRepo{ctrl: ctrl}
	mock.recorder = &MockBuyerRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuyerRepo) EXPECT() *MockBuyerRepoMockRecorder {
	return m.recorder
}
