// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package mock_authentication is a generated GoMock package.
package mock_authentication

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAuthenticationRepo is a mock of AuthenticationRepo interface.
type MockAuthenticationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticationRepoMockRecorder
}

// MockAuthenticationRepoMockRecorder is the mock recorder for MockAuthenticationRepo.
type MockAuthenticationRepoMockRecorder struct {
	mock *MockAuthenticationRepo
}

// NewMockAuthenticationRepo creates a new mock instance.
func NewMockAuthenticationRepo(ctrl *gomock.Controller) *MockAuthenticationRepo {
	mock := &MockAuthenticationRepo{ctrl: ctrl}
	mock.recorder = &MockAuthenticationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticationRepo) EXPECT() *MockAuthenticationRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuthenticationRepo) Create(ctx context.Context, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAuthenticationRepoMockRecorder) Create(ctx, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuthenticationRepo)(nil).Create), ctx, refreshToken)
}
