// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package mock_authentication is a generated GoMock package.
package mock_authentication

import (
	gomock "github.com/golang/mock/gomock"
)

// MockAuthenticationRepo is a mock of AuthenticationRepo interface.
type MockAuthenticationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticationRepoMockRecorder
}

// MockAuthenticationRepoMockRecorder is the mock recorder for MockAuthenticationRepo.
type MockAuthenticationRepoMockRecorder struct {
	mock *MockAuthenticationRepo
}

// NewMockAuthenticationRepo creates a new mock instance.
func NewMockAuthenticationRepo(ctrl *gomock.Controller) *MockAuthenticationRepo {
	mock := &MockAuthenticationRepo{ctrl: ctrl}
	mock.recorder = &MockAuthenticationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticationRepo) EXPECT() *MockAuthenticationRepoMockRecorder {
	return m.recorder
}
