# Database credentials
db:
  user: ""
  pass: ""
  host: ""
  db: ""
  port: 5432
  loglevel: 4 # 1 (silent) - 4 (info)
  maxidlecon: 10
  maxopencon: 100
  conmaxlifetime: 3600 # in seconds

# JWT
jwt:
  keyaccess: ""
  keyrefresh: ""
  expiryageaccess:
    value: 0
    unit: "hour" # hour, minute, or second
  expiryagerefresh:
    value: 0
    unit: "hour" # hour, minute, or second

